Add SonarCloud integration for quality checks and coverage reports

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -63,6 +63,13 @@ jobs:
         name: backend-coverage
         path: backend/coverage/
 
+    - name: SonarCloud Scan
+      uses: sonarsource/sonarcloud-github-action@v1.5
+      with:
+        projectBaseDir: backend
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
     - name: Store build artifacts
       uses: actions/upload-artifact@v4
       with:
@@ -139,6 +146,19 @@ jobs:
 
     - name: Debug environment variables
       run: printenv | grep FIREBASE
+
+    - name: Check SonarCloud Quality Gate
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+        STATUS=$(curl -s -u $SONAR_TOKEN: \
+          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=PajovicVanja_RIRSsolo" \
+          | jq -r '.projectStatus.status')
+        echo "Quality Gate Status: $STATUS"
+        if [ "$STATUS" != "OK" ]; then
+          echo "Quality Gate failed. Stopping the pipeline."
+          exit 1
+        fi
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -62,6 +62,13 @@ jobs:
         name: frontend-coverage
         path: frontend/coverage/
 
+    - name: SonarCloud Scan
+      uses: sonarsource/sonarcloud-github-action@v1.5
+      with:
+        projectBaseDir: frontend
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
   deploy-to-development:
     runs-on: ubuntu-latest
     needs: build-and-test
@@ -103,6 +110,19 @@ jobs:
       with:
         name: frontend-build
         path: frontend/build
+
+    - name: Check SonarCloud Quality Gate
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      run: |
+        STATUS=$(curl -s -u $SONAR_TOKEN: \
+          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=PajovicVanja_RIRSsolo" \
+          | jq -r '.projectStatus.status')
+        echo "Quality Gate Status: $STATUS"
+        if [ "$STATUS" != "OK" ]; then
+          echo "Quality Gate failed. Stopping the pipeline."
+          exit 1
+        fi
 
     - name: Deploy to Firebase Hosting (Production)
       env:
